### ISSUE TITLE
Concluir AppServices_POST

### ISSUE THREAD

**Issue by paulojna** [UMinho-Netedge/netedge-mep-uminho#5]

**Comment by vinicf** [comment]
O Post está a salvar os serviços no mongo.

**Comment by vinicf** [comment]
Agora há uma verificação do appStatus, apenas aceita-se o registro de um serviço, caso o appStatus seja IndicationType.READY

**Comment by vinicf** [comment]
O código de erro 403 Forbidden foi testado com alterações diretas no mongo. 
Devo finalizar as mensagens de erro e posteriormente checar os procedimentos relativos às subscriptions.

**Comment by vinicf** [comment]
Acrescentei uma tarefa denominada "Manipulação de erros" para definir o tratamento de erros a ser dado.

**Comment by vinicf** [comment]
Aguardando review para fazer merge com dev.

**Comment by adcosta** [comment]
Review feita. Pode fazer o merge sem dúvidas. Acho que devemos ver depois os copywrites das files, que continuam a ter apenas IT, mas já começa a haver muito mais da nossa parte.
