### ISSUE TITLE
Verificar query e retorno de Services_GET

### ISSUE THREAD

**Issue by paulojna** [UMinho-Netedge/netedge-mep-uminho#6]
GET /applications/services

- [x] query a filtrar a collection pelos valores procurados
- [x] schema a garantir exclusão mútua
- [x] validação do formato UUID no serInstanceId
- [x] Tratamento de erros e envio de uma instância ProblemDetails

**Comment by jnbastos** [comment]
Alterações feitas em:
models.py
schemas.py
services_controller.py
utils.py

**Comment by nflori** [comment]
Olá João,


  Qual o link onde estão as mais recentes versões do abaixo?

models.py

schemas.py
services_controller.py
utils.py


Obrigado.


Nicolás

________________________________
De: João Bastos ***@***.***>
Enviado: 12 de julho de 2022 16:45:58
Para: UMinho-Netedge/netedge-mep-uminho
Cc: Nicolas Francisco Lori; Assign
Assunto: Re: [UMinho-Netedge/netedge-mep-uminho] Verificar query e retorno de Services_GET (Issue #6)


Alterações feitas em:
models.py
schemas.py
services_controller.py
utils.py

**Comment by nflori** [comment]
Perguntas de Nicolas e respostas de João Bastos:
1) acerca do models.py: como consegues passar de 2 blocos que definem o dict para apenas um bloco?
    As linhas 821 a 835 form removidas porque ainda estava em fase de testes e estava a tentar perceber como funciona o mecanismo. Mas depois vi que o melhor seria criar a função interna bool_conv. Na remoção da 809 a 819 que depois virou em adição das 813 a 821 se reparar a única alteração foi mesmo de identação pois acrescentei mais um tab,

2) acerca do schemas.py: porque é que os "not required" mudaram?
    Porque não estavam a garantir a exclusão mútua do ser_instance_id, ser_category_id e ser_name, então alterei para quando fizer validate ele recorra ao schema e ele lance um erro caso não haja a tal exclusão mútua.

**Comment by nflori** [comment]
Declaração de João Bastos:
  Já corrigi a validação do formato UUID para o caso em que se passa uma lista de ser_instance_ids. No gitKraken pode se ver o update com a descrição "Update services_get: validate UUID format for multiple ser_instance_id" onde se encontram modificações em dois ficheiros mas a única que interessa é do services_controller.py.

Resposta de Nicolas Lori:
   Vi e pareceu-me bem.
